/**
 * ==========================================================
 * Interest Ontology
 * ==========================================================
 *
 * '빠지', '글램핑'처럼 관광지명이 아니라
 * 하고 싶은 활동을 말하는 표현을 관광 테마로 매핑한다.
 *
 * 오른쪽 값은 DB의 middleCategory와 같아야 한다.
 * 추천 질의가 middleCategory로 후보를 거르기 때문이다.
 *
 * 키워드는 공백을 지운 문장에 substring으로 대조하므로
 * '산', '절'처럼 다른 낱말에 섞여 드는 한 글자 표현은 두지 않는다.
 * ==========================================================
 */

module.exports = {
    자연관광: [
        "자연경관",
        "자연",
        "경치",
        "풍경",
        "등산",
        "산행",
        "산책",
        "둘레길",
        "숲길",
        "휴양림",
        "계곡",
        "폭포",
        "호수",
        "강변",
        "해변",
        "바다",
        "수목원",
        "식물원",
        "단풍",
        "벚꽃",
        "꽃구경",
        "꽃놀이",
        "일출",
        "일몰",
        "노을",
        "별보",
        "별구경",

        // 영어
        "nature",
        "scenery",
        "scenic",
        "mountain",
        "hiking",
        "hike",
        "trekking",
        "trail",
        "valley",
        "waterfall",
        "lake",
        "river",
        "beach",
        "arboretum",
        "botanical garden",
        "forest",
        "autumn leaves",
        "fall foliage",
        "cherry blossom",
        "sunrise",
        "sunset",
        "stargazing",
        "nature walk",
    ],

    레저스포츠: [
        "빠지",
        "수상레저",
        "수상스키",
        "웨이크보드",
        "제트스키",
        "래프팅",
        "카약",
        "카누",
        "패들보드",
        "서핑",
        "물놀이",
        "워터파크",
        "수영",
        "낚시",
        "캠핑",
        "글램핑",
        "차박",
        "자전거",
        "라이딩",
        "레일바이크",
        "짚라인",
        "집라인",
        "번지점프",
        "패러글라이딩",
        "승마",
        "골프",
        "스키장",
        "스노보드",
        "액티비티",
        "레저",
        "스포츠",

        // 영어
        "water sports",
        "water leisure",
        "wakeboard",
        "water ski",
        "jet ski",
        "rafting",
        "kayak",
        "canoe",
        "paddleboard",
        "surfing",
        "swimming",
        "fishing",
        "camping",
        "glamping",
        "car camping",
        "cycling",
        "biking",
        "rail bike",
        "zipline",
        "zip line",
        "bungee",
        "paragliding",
        "horseback riding",
        "golf",
        "skiing",
        "snowboarding",
        "activity",
        "activities",
        "leisure",
        "water park",
    ],

    문화관광: [
        "박물관",
        "미술관",
        "전시",
        "공연",
        "연극",
        "뮤지컬",
        "콘서트",
        "축제",
        "테마파크",
        "놀이공원",
        "공원",
        "전망대",
        "랜드마크",
        "야경",
        "카페",
        "문화",

        // 영어
        "museum",
        "art museum",
        "gallery",
        "exhibition",
        "exhibit",
        "performance",
        "musical",
        "concert",
        "festival",
        "theme park",
        "amusement park",
        "observatory",
        "observation deck",
        "landmark",
        "night view",
        "cafe",
        "culture",
        "cultural",
    ],

    역사관광: [
        "역사",
        "유적",
        "고궁",
        "궁궐",
        "왕릉",
        "고분",
        "사찰",
        "고찰",
        "서원",
        "향교",
        "성곽",
        "한옥",
        "민속마을",
        "전통마을",
        "전통문화",

        // 영어
        "history",
        "historic",
        "historical",
        "heritage",
        "ruins",
        "palace",
        "royal tomb",
        "temple",
        "shrine",
        "fortress",
        "hanok",
        "traditional village",
        "folk village",
    ],

    체험관광: [
        "체험",
        "공예",
        "도자기",
        "만들기",
        "농장",
        "목장",
        "과일따기",
        "딸기따기",
        "수확",
        "온천",
        "스파",
        "찜질",
        "웰니스",
        "힐링",
        "명상",
        "템플스테이",

        // 영어
        "hands-on",
        "handicraft",
        "craft",
        "pottery",
        "farm",
        "ranch",
        "fruit picking",
        "harvest",
        "hot spring",
        "spa",
        "sauna",
        "wellness",
        "healing",
        "meditation",
        "temple stay",
    ],

    쇼핑: [
        "쇼핑",
        "시장",
        "아울렛",
        "백화점",
        "대형마트",
        "면세점",

        // 영어
        "shopping",
        "market",
        "outlet",
        "department store",
        "duty free",
        "mall",
    ],
};
